version: 2
updates:
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  #  Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  #  Enable version updates for npm (backend)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  #  Enable version updates for Docker (backend)
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"