# @Author: Brogan Miner <Brogan>
# @Date:   2018-12-20T10:38:57-08:00
# @Email:  brogan.miner@oregonstate.edu
# @Last modified by:   Brogan
<<<<<<< HEAD
# @Last modified time: 2019-01-04T13:44:38-08:00
=======
# @Last modified time: 2018-12-21T15:02:39-08:00
>>>>>>> 243757575dbfdcefe0d1addeb9f058f6eb2cafea

language: node_js
python:
- '2.7'
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_3e7d443718a9_key -iv $encrypted_3e7d443718a9_iv
  -in .env.enc -out .env -d
- mv .env tests/.env
cache:
  directories:
  - node_modules
  - "$HOME/.local"
script:
<<<<<<< HEAD
- npm run test:unit
- |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run build
    echo "dashboard.sustainability.oregonstate.edu" >> dist/CNAME
  else
    npm run build-stage
  fi

=======
- npm test
- npm run build
- echo "dashboard.sustainability.oregonstate.edu" >> dist/CNAME
>>>>>>> 243757575dbfdcefe0d1addeb9f058f6eb2cafea
deploy:
- provider: pages
  local-dir: dist/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
- provider: s3
  access_key_id: "$S3_ACCESS_ID"
  secret_access_key: "$S3_ACCESS_KEY"
  bucket: energy-dashboard
  skip_cleanup: true
  local_dir: dist
  on:
    all_branches: true
<<<<<<< HEAD
    condition: $TRAVIS_BRANCH != master
# after_deploy:
# - mocha tests/integration.js
=======
after_deploy:
- mocha tests/integration.js
>>>>>>> 243757575dbfdcefe0d1addeb9f058f6eb2cafea
