# syntax=docker/dockerfile:1
FROM node:12 as TestRunner
WORKDIR /test_work_dir
COPY package*.json ./
RUN npm install
COPY . ./
CMD ["./wait-for-it.sh", "db:3306", "-t", "40", "--", "npm", "run", "test"]