version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE: "energy"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  test:
    build: .
    depends_on: 
      - db
    environment:
      MYSQL_HOST: db