services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE: "energy"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  test:
    build: .
    depends_on: 
      - db
    command: ["./wait-for-it.sh", "db:3306", "-t", "60", "--", "npm", "run", "test"]
    environment:
      MYSQL_HOST: db