INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (1,'265115620','tebeau.jpg','Residence','Tebeau Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (2,'100278455','wavelab.jpg','Academics','Hindsdale Wave Lab',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (3,'40535383','0014_OSUBiz_3223.jpg','Events & Admin','Memorial Union',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (4,'40535423','milne.jpg','Academics','Milne Computer Center',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (5,'92994898','dryden.jpg','Academics','Dryden Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (6,'92370509','4172-Campus-0195.jpg','Academics','Kelley Engineering Center',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (7,'41375968','sackett.jpg','Residence','Sackett Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (8,'91778492','cauthorn_2.jpg','Residence','Cauthorn Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (9,'40535502','180626_teresahall_2117.jpg','Academics','Valley Library',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (10,'45088438','Oregon-State-University-Dixon-Rec-Center-Aquatic-Center-Corvallis-Oregon.jpg','Athletics & Rec','Dixon Rec Center',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (11,'91780165','west-hall.jpg','Residence','West Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (12,'91780166','marketplacewest.jpg','Dining','West Dining Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (14,'92962627','arnold.jpg','Dining','Arnold Dining Center',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (15,'92962598','bloss_2.jpg','Residence','Bloss Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (16,'91778510','buxton_2.jpg','Residence','Buxton Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (17,'92962590','OSU_alumni_center.jpg','Events & Admin','CHM2Hill Alumni Center',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (18,'92946879','callahan_v2_0.jpg','Residence','Callahan Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (19,'92962630','finley.jpg','Residence','Finley Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (20,'41376076','gill.jpg','Athletics & Rec','Gill Coliseum',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (21,'92962632','Halsell_4.jpg','Residence','Halsell Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (22,'91778515','hawley_2.jpg','Residence','Hawley Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (23,'136374085','illc.jpg','Residence','ILLC',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (24,'346414624','Lester_060517_1173.jpg','Academics','Johnson Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (25,'92946852','mcnary_dining.jpg','Dining','McNary Dining Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (26,'92946874','mcnary_2.jpg','Residence','McNary Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (27,'40535366','smilam.jpg','Academics','Milam Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (28,'41376092','Nashhall-1_905.jpg','Academics','Nash Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (29,'788678967','poling_2.jpg','Residence','Poling Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (30,'265112825','sec.jpg','Events & Admin','Student Experience Center',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (31,'54119130','OSU_WenigerHall_35.jpg','Academics','Weniger Hall',1);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (32,'92946844','wilson_hall.jpg','Residence','Wilson Hall',NULL);
INSERT INTO `` (`id`,`map_id`,`image`,`group`,`name`,`hidden`) VALUES (34,'',NULL,'','Orchard Court',1);
