INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (8,'Tebeau Hall',1,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (9,'Memorial Union',3,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (10,'Milne Computer Center',4,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (11,'Dryden Hall',5,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (12,'McNary Dining Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (13,'McNary Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (14,'Dixon Recreation Center',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (15,'Hawley Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (16,'Buxton Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (17,'Sackett Hall',7,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (18,'Wilson Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (19,'Callahan Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (20,'Poling Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (21,'Bloss Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (22,'Finley Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (23,'Arnold Dining Center',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (24,'Valley Library',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (25,'Kelley Engineering Center',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (26,'Student Experience Center',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (27,'West Hall',11,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (28,'West Dining Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (29,'Johnson Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (30,'Nash Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (31,'Weniger Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (32,'Cauthorn Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (33,'Gill Coliseum',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (34,'CH2MHill Alumni Center',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (35,'Halsell Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (36,'Milam Hall',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (37,'ILLC',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (38,'Wave Lab',2,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (39,'Orchard Court',NULL,NULL);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (52,'Kelley Engineering Center',6,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (54,'Cauthorn Hall',8,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (55,'Valley Library',9,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (56,'Dixon Rec Center',10,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (58,'West Dining Hall',12,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (59,'Cauthorn',13,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (60,'Dixon Steam',10,1);
INSERT INTO `` (`id`,`name`,`building_id`,`default`) VALUES (61,'Arnold Electric',14,1);
