INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (1,'Tebeau Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (2,'McNary Complex Master Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (3,'Valley Library Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (4,'Sackett Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (5,'Dixon Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (6,'McNary Hall Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (7,'Dixon Steam','s',4444);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (8,'Memorial Union West Electricity (2000A)','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (9,'Memorial Union East Electricity (1000A)','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (10,'Arnold Dining Electrical Main','e',5);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (11,'Central feeder distribution panel (SDP-1)','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (12,'My New Device','e',4025);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (13,'Bloss Hall Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (14,'West mechanical room distribution panel (SD-W)','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (15,'Filnley Hall Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (16,'Arnold Dining Chiller Electricity','e',2);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (17,'My New Device','e',4025);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (18,'Halsell Hall Electricity','e',4045);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (19,'Internal I/O','e',27);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (20,'4M-1A','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (21,'X-3','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (22,'4L-1A','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (23,'4M-PHA','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (24,'ATS-LS','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (25,'SPARE 100A','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (26,'SPARE 225A','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (27,'Internal I/O','e',27);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (28,'ILLC Electricity','e',82);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (29,'Student Experience Center Steam','s',4444);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (30,'Student Experience Center Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (31,'Nash 1500 Amp Electrical','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (32,'Nash 3000 Amp Electrical','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (33,'4000A service','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (34,'2000A Service','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (35,'Weniger South Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (36,'Milne South Electrical','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (37,'Milne North Electrical','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (38,'Buxton Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (39,'Hawley Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (40,'Dryden Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (41,'Callahan Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (42,'Wilson Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (43,'Poling Electricity','e',4045);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (44,'West Hall Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (45,'Cauthorn Hall Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (46,'West Dining','e',2);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (47,'Gill','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (48,'Internal I/O','e',27);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (49,'Milam Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (50,'CH2MHill Alumni Center Electricity Old','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (51,'CH2MHill Alumni Center Electricity New','e',2);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (52,'CH2MHill Alumni Center Modhopper','g',17);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (53,'Buxton Electricity','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (54,NULL,NULL,NULL,null);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (55,'Main Johnson Hall','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (56,'X-7','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (57,'X-9','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (58,'S4P-PHA','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (59,'X-10','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (60,'S4P-1A','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (61,'SPARE 200A','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (62,'Wave Tank # 1','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (63,'Wave Tank # 2','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (64,'Wave Tank # 3','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (65,'Wave Tank # 4','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (66,'Wave Tank HVAC','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (67,'Building Main','e',48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (68,'Orchard Court',NULL,48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (69,'West Side Wave Tank',NULL,48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (70,'Main Pump Disconnect',NULL,48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (71,'Wave Machine',NULL,48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (72,'Kelley Steam','s',4444);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (73,'Nash Steam','s',4444);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (75,'Test Meter',NULL,2);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (76,'Test Meter',NULL,2);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (77,'Valley Library Electric',NULL,48);
INSERT INTO `` (`id`,`name`,`type`,`class`) VALUES (78,'Red Lion',NULL,4444);
