name: SAM Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy-sam:
    name: Deploy Serveless API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Deploy
      working-directory: backend
      run: |
        sam validate
        sam package --template-file template.yaml --s3-bucket osu-so-serverless-builds --output-template-file packaged.yaml
        sam deploy --template-file /home/runner/work/energy-dashboard/energy-dashboard/backend/packaged.yaml --stack-name energy --capabilities CAPABILITY_IAM --region us-west-2 --no-confirm-changeset --no-fail-on-empty-changeset
