name: gh pages
on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: unit tests
        working-directory: backend
        run: |
          docker compose build
          docker compose run --rm test
          docker compose down

  build-deploy-gh-pages:
    name: Build / Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm ci
        run: |
          npm ci
      - name: npm build frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run build
      - name: deploy frontend to gh pages
        uses: crazy-max/ghaction-github-pages@v4     # https://github.com/crazy-max/ghaction-github-pages
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: dashboard.sustainability.oregonstate.edu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
