
name: S3 Frontend Test Build
on:
  push:
    branches-ignore:
      - master
      - gh-pages
jobs:
  deploy-s3:
    name: Deploy to S3 Test Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: unit tests
      working-directory: backend
      run: |
        docker-compose build
        docker-compose run --rm test
        docker-compose down
    - name: npm install and build frontend
      run: |
          npm install
          npm run build-stage
    - name: deploy frontend
      run: |
        aws s3 sync ./dist s3://energy-dashboard